object Versions {
    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val material = "1.9.0"
    const val constraintlayout = "2.1.4"
    const val coroutines = "1.7.1"
    const val webkit = "1.6.1"
    const val apacheCommonsText = "1.10.0"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val juint = "4.13.2"
    const val extJunit = "1.1.5"
    const val espressoCore = "3.5.1"
    const val gradle = "8.1.0"
    const val kotlin = "1.8.0"
    const val room = "2.5.2"
    const val ksp = "1.8.10-1.0.9"
}